sylius_grid:
  grids:
    monsieurbiz_homepage:
      driver:
        name: doctrine/orm
        options:
          class: '%monsieurbiz_homepage.model.homepage.class%'
          repository:
            method: createListQueryBuilder
            arguments: ["%locale%"]
      limits: [25, 50, 100, 200]
      sorting:
        id: desc
      fields:
        id:
          type: string
          label: monsieurbiz_homepage.ui.form.id
          sortable: ~
        name:
          type: string
          label: monsieurbiz_homepage.ui.form.name
          sortable: translation.name
        channels:
          type: twig
          label: sylius.ui.channels
          options:
            template: '@SyliusAdmin/Grid/Field/_channels.html.twig'
      actions:
        main:
          create:
            type: create
            label: monsieurbiz_homepage.ui.actions.create
        item:
          update:
            type: update
          delete:
            type: delete
      filters:
        name:
          type: string
          label: monsieurbiz_homepage.ui.form.name
          options:
            fields: [ translation.name ]
        content:
          type: string
          label: monsieurbiz_homepage.ui.form.content
          options:
            fields: [ translation.content ]
        channel:
          type: entity
          label: sylius.ui.channel
          options:
            fields: [ channels.id ]
          form_options:
            class: "%sylius.model.channel.class%"
