monsieurbiz_sylius_homepage_admin:
    resource: |
        alias: monsieurbiz_homepage.homepage
        section: admin
        permission: true
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: monsieurbiz_homepage
        vars:
            all:
                subheader: monsieurbiz_homepage.ui.homepages_subheader
                templates:
                    form: "@MonsieurBizSyliusHomepagePlugin/Admin/Homepage/_form.html.twig"
            index:
                icon: 'home'
    type: sylius.resource
